name = "MGXAmplicon"
uuid = "63a10644-c7ba-4856-84e7-67b6bcc4decd"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Chain = "8be319e6-bccf-4806-a6f7-6fae938471bc"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Microbiome = "3bd8f0ae-a0f2-5238-a5af-e1b399a4940c"

[compat]
julia = "1.6"